name: Waka Readme

on:
  push:
    branches:
      - master
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC
    - cron: "25 16 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
